In [2]:
import pandas as pd
import numpy as np
import os

print(os.getcwd())

/home/python_user/coding/ds/kaggle/s6e6_star


In [3]:
data_array = np.load('artifacts/tune_xgb_params_v1_ve4_no_te_target_weight/tune_xgb_params_v1_ve4_no_te_target_weight_oof.npy')



In [4]:
print(data_array)

[[9.99806702e-01 1.49587169e-04 4.36971895e-05]
 [9.65307713e-01 6.56728807e-04 3.40356007e-02]
 [4.04335806e-05 9.99956727e-01 2.84954876e-06]
 ...
 [9.98847723e-01 9.81489546e-04 1.70802276e-04]
 [8.89422372e-05 9.99903440e-01 7.59287150e-06]
 [8.95129400e-04 9.99069631e-01 3.52368224e-05]]
